### ISSUE TITLE
SP3-T1: SmapiController.getSubscriberAccount

### ISSUE THREAD

**Issue by van-c-nguyen** [Clearleap/cxapp#6]
Create the getSubscriberAccount method of the SmapiController. After it processed the request, it needs to call the CxService.getSubscriber API.

**Comment by ranjith-ibs** [comment]
@van-c-nguyen Could you please clarify if the account element in the response should have identityGuid or accountGuid. In the table it is mentioned as identityGuid while in samples it is accountGuid.

**Comment by van-c-nguyen** [comment]
It is the identityGuid and I already fixed the typo in the SDD.

**Comment by van-c-nguyen** [comment]
Close the task.

**Comment by ranjith-ibs** [comment]
Task completed and code merged.
