### ISSUE TITLE
SP3-T3: CxService.refreshSubscriberStatus Part 1

### ISSUE THREAD

**Issue by van-c-nguyen** [Clearleap/cxapp#8]
Create the refreshSubscriberStatus of the CxService class. It needs to performs steps 1.1 - 1.2 and skips steps 1.3 - 1.16 in the 4.7.3 Sequential Diagram of the SDD for retrieving subscriber only. In Part 2, it will also return the subscription after it checks the subscription status.

Coding Estimated Hours =?
QA Estimate Hours =?

**Comment by ranjith-ibs** [comment]
This was completed as part of https://github.com/Clearleap/cxapp/pull/25
